elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
  labels:
    container-role: elasticsearch
  container_name: elasticsearch
  restart: always
  ports:
   - "9200:9200"
   - "9300:9300"

logstash:
  image: docker.elastic.co/logstash/logstash:5.2.1
  labels:
    container-role: logstash
  container_name: logstash
  restart: always
  ports:
   - "5000:5000"
  links:
   - elasticsearch

kibana:
  image: docker.elastic.co/kibana/kibana:5.2.1
  labels:
    container-role: kibana
  container_name: kibana
  restart: always
  links:
   - elasticsearch
  ports:
   - "5601:5601"
